### ISSUE TITLE
Option to disable 'Select background image for...' when importing metadata

### ISSUE THREAD

**Issue by meowthed** [JosefNemec/PlayniteExtensions#105]
This function does work, but I don't really want to use it regularly.

**Comment by Terrance** [comment]
I was about to raise an issue in the main repo about skipping the background choice prompt during general library imports, but here looks like a place to voice more support...

For large imports of new games (e.g. game bundles, enabling a new integration), I have to continuously select a background for many of the games that offer multiple, which means I can't leave the import unattended as it sits waiting for an answer each time. The prompt also interrupts any business in other apps whilst I'm waiting, which is rather annoying.  I'm really not fussed what background image is used so I'd quite like it to just take the first one.

Concrete example, importing the large itch.io bundles after claiming the games:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/4025899/d13027aa-5a2d-442b-bff1-65259bdeece5)
Maybe 10-20% of these are prompting for a preferred background.

I note the (third-party) IndieGala integration offers this option:
![image](https://github.com/JosefNemec/PlayniteExtensions/assets/4025899/69c6011d-4b3f-409d-98ab-e02903f4bcb5)
This would be useful to have as a general library import option, rather than every integration having to do it themselves.

**Comment by JosefNemec** [comment]
> This would be useful to have as a general library import option, rather than every integration having to do it themselves.

Not possible, Playnite has no control over how these images are downloaded, we ask metadata plugin for an image and how that plugin gets it (including showing some dialogs) is up to each plugin individually.

Plugins can already detect when  a download is in background or manual one and act accordingly, like IGDB one does for example, so if you are getting some dialogs during background download, I recommend raising an issue with plugins showing dialogs.
