### ISSUE TITLE
Last Played data is blank for Epic

### ISSUE THREAD

**Issue by Barleyman** [JosefNemec/PlayniteExtensions#139]
**Describe the bug**
As in the title, none of the Epic games have anything ("Never") on the "last played" field, even if there is playtime reported. Therefore the games are sorted in a semi-random order if you ask sort by "last played".

**To Reproduce**
Open epic store library view. Sort by last played date. Observe where the games you played last are. Check the last played field in the game info. 

**Diagnostics ID**
67b6a4e1-de8f-491e-9a2c-d4f94ab9ac3c

**Comment by darklinkpower** [comment]
Last Played date is not imported for newly added games from the Epic library, there's no available way to obtain this information, only Playtime. Playnite will correctly start tracking the Last Played date when you start launching games from Playnite.

**Comment by Barleyman** [comment]
@darklinkpower Is that so? On a quick check, this seems to apply for GOG galaxy with their official Epic integration as well, so probably that's accurate. 

This could be mentioned in the "known issues" list for EGS, I can see it's on the library feature list table, although "Play time import" is misleading as play time *is* imported.

**Comment by darklinkpower** [comment]
You must be referring to this table: https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider

I don't think Playtime is misleading, it refers to the value in Edit -> Advanced -> Time played. I don't think I've seen people confuse this with Last played before.

Regarding adding to known issues, I don't think this should be considered an issue because it's not an issue per definition and it's not indicated anywhere that this is a feature that should be or is supported. Perhaps adding this to the table so people know this is not implemented would be more appropriate.

**Comment by Barleyman** [comment]
Hey, "time played" **does** work from Epic, the table is in error.

For me personally having most recently played games on top of the list is much more relevant than total game time which is a curiosity but that's besides the point. If it's not possible to extract the last played time from EGS, it's not.

**Comment by JosefNemec** [comment]
Closing, as darklinkpower said, there's currently no way we can currently obtain that info.
