### ISSUE TITLE
[Epic] Support for Heroic Launcher

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/PlayniteExtensions#153]
**Describe the solution you'd like**
Support for Heroic Launcher installed games

Is there a possibility to detect games installed by Heroic Launcher / legendary instead (or in addition) to epic games launcher installed games?

I can do edit my library entries manually, but this is a real hassle to do...

**Comment by JosefNemec** [comment]
I have no plans supporting unofficial 3rd party implementations like Heroic at the moment. It would imo make more sense creating separate integration plugin that's specifically targeting Heroic (maybe even integrating Legendary instead and cutting out Heroic completely).

However, since I already have a lot of these plugins to maintain, I will definitely not be creating any new ones. Somebody from the community would have to do it instead (like was the cases for several stores already).
