### ISSUE TITLE
itch io integration error during game import

### ISSUE THREAD

**Issue by DaLimCodes** [JosefNemec/PlayniteExtensions#167]
### Bug Description

Whenever there is a request to import game, I get a notification saying

Failed to import games from itch.io.
The requested address is not valid in its context 127.0.0.1:3222

PS: note that the port number always changes whenever I do import game request

Looking at netstats and task manager, the application that is using that port number is an application named butler.exe as far as I can tell, but since I cannot find any log files of this process at all I cannot decipher exactly what this error message is saying unfortunately.

I checked firewall for itch, butler.exe, Playnite.DesktopApp.exe, and Playnite.FullscreenApp.exe and they're all certainly not blocked. In fact, I even tried disabling windows firewall completely and I'm still getting the same exact error message as above.

I also checked my antivirus which is called windows security in Windows 11, but I think it used to be called windows defender on Windows 10, and I don't believe any of these programs are blocked either, otherwise I would have gotten alerts.

At this point, I'm genuinely out of idea and hence why I'm raising this bug report :/

I believe the issue started after I migrated from Windows 10 to Windows 11, but again, I checked my firewall and antivirus with no luck at all, so I'm genuinely unsure what else I could do aside from raising this bug report.

If there's any step that I can run in order to do debugging, I would be more than happy to run it and report back!

### Diagnostics ID

2fdce77a-60f6-4b37-9e8f-1630a5ef03db

### Screenshots

![image](https://user-images.githubusercontent.com/3626687/161725181-69739af3-1f89-4234-a92e-30e2243f0a2d.png)

**Comment by JosefNemec** [comment]
Please test it with [this version](https://playnite.link/download/ItchioLibrary_Builtin_2_4.pext) of itch plugin, just download and run that file.

**Comment by DaLimCodes** [comment]
Hey there, I closed my Playnite and itch and made sure all butler.exe processes are dead first.

Then I ran the file you provided above and was prompted to install version 2.4 (which I'm on currently?) as you can see below
![image](https://user-images.githubusercontent.com/3626687/161738946-c2bb4b28-fdef-4756-97ac-34c58d2c6d08.png)

Regardless, I clicked yes and then accepted the application restart prompt.

Shortly afterward, playnite client is running as usual with no alert, so clicked the playnite button on top left -> Update Game Library -> itch.io, sadly I am then greeted by the same error message
![image](https://user-images.githubusercontent.com/3626687/161739328-79d4b452-e53b-4d13-a6f2-a0368e09cc67.png)

**Comment by JosefNemec** [comment]
I'm afraid I'm out of ideas. I can't reproduce it myself and there's really not that much information about this error out there and what there is is not relevant to this case. I'm suspecting it's some issue with your system or 3rd party app installed on your system, since this is the only report of this issue since itch plugin was created (the way we connect to bulter hasn't changed since then).

And yes, that installation dialog was correct, it's just re-built 2.4 with some changes, same version number.

**Comment by DaLimCodes** [comment]
Thanks, I appreciate the attempt regardless.

Hm, I wonder if there's a way to run it under some sort of debug mode or get it output logs of some sort

**Comment by JosefNemec** [comment]
The error occurs in base .NET library and I haven't found a way to get more/debug information when this error happens. It is really weird, especially if you say that itch client itself works properly.

I also tried to reproduce it in Win 11 virtual machine and it seems to work just fine, so it's not a Windows 11 issue.

The only other option would be rewriting itch plugin to use different TCP library, but I don't have time to do that. And since the base .NET one has been used in ton of projects, I would expect to be able to find some information about this issue if it was in fact issue in the library.

**Comment by DaLimCodes** [comment]
I'm closing this ticket now. In the end, I had to create a new windows account since reinstalling both playnite and itch client app still does not resolve the issue
