### ISSUE TITLE
Epic logs out on every restart

### ISSUE THREAD

**Issue by blackparadox** [JosefNemec/PlayniteExtensions#195]
For about a two weeks now, every time my PC reboots Playnite's "Epic Settings" revert to "Requires authentication" - Neither the Epic website (through Firefox), nor the Epic launcher have this issue, and retain my login for 30 days.

"Remember me" is ticked when authenticating, and cookies should not be cleared on shutdown.

The issue does not occur when restarting Playnite within the same Windows session, only after a reboot.

Diagnostics ID: 5ff3e6cc-606c-4455-8c0d-c06ba046c838

**Comment by JosefNemec** [comment]
Epic integrations doesn't do anything different in regards to app restarts vs system restarts. So most likely something is messing with auth token files in `%appdata%\Playnite\ExtensionsData\00000002-dbd1-46c6-b5d0-b1ba559d10e4` (or just install folder instead of appdata if you are using portable version).

Also that token file is encrypted with encryption tied to a Windows user account which created the file, so running Playnite under different user or syncing the file from different computer will invalidate authentication.
