### ISSUE TITLE
Cannot sign into Playstation/Verify account

### ISSUE THREAD

**Issue by NateIce31** [JosefNemec/PlayniteExtensions#26]
Had already logged in at some point however it now asks me to log in again.
Every time I attempt to log in however, I get a password incorrect error. I also tried using a device setup password from Sony but no luck.
Any suggestions?

**Comment by EdisonTheFox** [comment]
I too am having this issue. Attached a screenshot of what I am seeing.

> Playnite 8.14 Running on Windows 11 Build 22000.71
![image](https://user-images.githubusercontent.com/45759577/126049989-08d5873a-99fe-415e-b8d3-95769f76605e.png)

**Comment by JosefNemec** [comment]
Just heads up: I'm not working on PSN integration anymore, at least not until Playnite 9 is fully out. So if anybody else wants to fix this, feel free to do so.

**Comment by XenorPLxx** [comment]
I'm following a parallel discussion for GOG Galaxy and seems like someone started to figure out the new API, someone here might find it useful as well https://gist.github.com/sebj/239fb074429f632b4508c48cb2344cc6.

**Comment by joyrider3774** [comment]
it's fixed in gog galaxy, looking at this code / commit it should be possible to implement similar fix for the plugin in c# but i don't know how to do all that stuff, would take me way to much time and probably end up writing crappy code. From what i see the method to get games using throphies does not work anymore however you can get a list of bought and played games as well as the ps5 games using that new system
https://github.com/FriendsOfGalaxy/galaxy-integration-psn/commit/d50b5bf4c44d08ee5214d26967ce26309521c06e

**Comment by JosefNemec** [comment]
Closing, PSN integration is now being developer by somebody else: https://github.com/XenorPLxx/playnite-library-psn
