### ISSUE TITLE
EA App playtime importing incorrectly

### ISSUE THREAD

**Issue by Jordan-Ch** [JosefNemec/PlayniteExtensions#273]
This trouble seems to be unique to games imported through EA Play. 

When the EA library is refreshed, playtimes revert back to the times that where grabbed on the initial import of the game. 
It is not grabbing the current playtime from EA Play. Overriding the playtime gets reversed on a library refresh or on each launch of playnite when the library is refreshed automatically. 

Happy to provide any information that is useful for squashing this bug.

**Comment by fgblomqvist** [comment]
I just installed Playnite so I can't comment on earlier state, but for me it's simply retrieving the wrong playtime for some/most games. I'm not sure what time it's retrieving but it's always lower than the actual time (listed in the EA client). Re-retrieving it doesn't work.

In total I have 7 games in my lib (that I've played). It has the correct time for 4 of those. Coincidentally, I have not touched those 4 games in probably 1+ years (much longer for some). I have played the other 3 games at some point in the last 6 months.

I took a quick look at the code and it looks like it's hitting some old Origin API, so I'm guessing EA doesn't update that one. We'd probably have to try to figure out/reverse engineer the EA app's new API. Bummer.

**Comment by JosefNemec** [comment]
The whole EA game import is huge mess right now after migration from Origin to EA App. We are still using old Origin APIs so it's possible they are not reporting correct data.

I spent a lot of time trying to reverse new EA App APIs but no luck making something reliable. I myself can't justify spending any more time on it since I have plenty of work to do on Playnite itself. So this is wontfix unless somebody else wants to reimplement EA library sync.
