### ISSUE TITLE
Game statistic (EA App) -> Star Wars Jedi: Fallen Order

### ISSUE THREAD

**Issue by Caddie2908** [JosefNemec/PlayniteExtensions#275]
### Feature description

Hello, I stumbled across playnite a few weeks ago and I absolutely love it !!!!

However, I have a problem with the "EA App" integration. 

I played "Star Wars Jedi: Fallen Order" for almost 58 hours. When importing, however, the game is displayed twice (2x EA App, i think this is a bug), each with a little more than 19 hours. 

I then changed the playing time manually and removed the double import (with exclusion list), but restarting Playnite imports the wrong value of playtime again. 

Now I can limit the import of game statistics to "new games", but then all game statistics are no longer synchronized. 

It would be great if there was a way in the future to prevent the re-import of game statistics for individual games (completed games for example) without having to hide or delete them.

greetings from germany and thanks for your app!

### Screenshots

![grafik](https://user-images.githubusercontent.com/129961916/230086884-1f128ee3-0e5e-41d2-9b3a-6c25dccef2d7.png)

**Comment by JosefNemec** [comment]
> Play time not importing correctly

Can occur if a game is played via EA Play subscription. There is no fix for now. The workaround is to manually fix play time and disable forced time sync in Playnite's general settings.

Will be fixed in future when support for EA Play games is properly added.

> Some games are imported multiple times

Can happen if a game have multiple variants like purchased, beta, trial, subscription version etc. We can't currently reliably detect these so just remove unwanted entries and add them to the import ignore list.
