### ISSUE TITLE
EA games through Epic not importing even after launching them

### ISSUE THREAD

**Issue by Brandon1212b** [JosefNemec/PlayniteExtensions#352]
**Check for existing issue**
Found existing issue but is closed here: https://github.com/JosefNemec/PlayniteExtensions/issues/235

**Describe the bug**
EA game through Epic should import via EA plugin by launching the game once. I tried launching FC24 from both epic and EA launchers but it will not show up on playnite.

1. updating playnite game library does not import to Playnite
2. launching the game on Epic and EA does not import to Playnite
3. reinstalling the game does not import to Playnite
4. waiting 24 hours after starting the game for it to show on playnite does not work

**To Reproduce**
Try importing FC 24 from epic games store

**Screenshots**
N/A

**Diagnostics ID**
3c5e78bd-08f3-4140-9041-534bef1d0224

**Comment by hawkeye116477** [comment]
Maybe that's related with https://github.com/derrod/legendary/pull/632. I mean it's newer game, so maybe something changed related with detection of that.

**Comment by JosefNemec** [comment]
The whole EA game import is huge mess right now after migration from Origin to EA App. We are still using old Origin APIs so it's possible they are not reporting correct data.

I spent a lot of time trying to reverse new EA App APIs but no luck making something reliable. I myself can't justify spending any more time on it since I have plenty of work to do on Playnite itself. So this is wontfix unless somebody else wants to reimplement EA library sync.
