### ISSUE TITLE
Authentication do not work for Humble library integration

### ISSUE THREAD

**Issue by DenGuzawr22** [JosefNemec/PlayniteExtensions#357]
Each time when I click "Authenticate" botton for Humble library integration I get a browser screen when I do my authentication. And then instead get the screen where I must insert the email confirmation code, my page reloaded and nothing happen.

**To Reproduce**
1. Click `Library ->  Configure Integration -> Humble`
2. Click `Authenticate`
3. Submit your credentials
4. **nothing happening**

**Diagnostics ID**
c34347e9-dc03-4311-8013-fc8e20f1c6c3

**Comment by JosefNemec** [comment]
Is this login via standard email/password or using Google account? I can't reproduce it using normal account, including account that has 2FA enabled.

However, signin using Google I get similar behavior to what you describe. The problem is that the same behavior happens even when logging into Humble using Firefox, so this is imo broken on Humble's or Google's side.

**Comment by DenGuzawr22** [comment]
I was logging via my Google account. 
Now, I've tried to authenticate using my password, and it works. Thank you!
