### ISSUE TITLE
[Ubisoft] Multiple games having tracking issues

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/PlayniteExtensions#373]
**Describe the bug**
Since a couple of weeks multiple games have been reported to have tracking issues with Ubisoft plugin.
Games are tracking only a couple of seconds and then revert to not played state.

Myself, I discovered it around the release of AC Mirage, and then it was loosing tracking for every subsequent game I tried, including new titles (Avatar, Prince of Persia), same as older ones that worked in the past (The Division, Assassin's Creed Remastered III, Immortals Fenyx Rising).

I've worked around the problem by adding a custom Play Action with folder tracking and delay of 60 seconds, this resolves the issue for me, but there have been additional reports on Discord that this is not solving the issue for Rainbow Six Siege.

**To Reproduce**
Run any of the games listed trough Playnite and observe tracking working only for couple of seconds.

**Comment by JosefNemec** [comment]
I can't reproduce it. The only game from what you mentioned I own is The Division and tracking of it works properly according to my tests (both when Uplay is already running and when it's not running prior to launching the game from Playnite). I also tried several other Uplay games and they are all tracked properly: 

- AC Odyssey
- Beyond Good and Evil
- R6 Siege
- Trackmania
- Trials Rising

So if this is somehow tied only to specific games you mentioned, it will need to be investigated and fixed by somebody who owns them. It's impossible for me personally to fix/diagnose this without having access to those games.

**Comment by XenorPLxx** [comment]
I should be able to try on some of them, including Trackmania and R6 Siege, I'll test it out and let you know.

**Comment by XenorPLxx** [comment]
Well, looks like Ubisoft fixed it. I've tried both games that previously had this problem and games from your list, also consulted with 2 other people who've had this problem, at least one confirming that it's tracking as expected now.
