### ISSUE TITLE
Can not log into epic account

### ISSUE THREAD

**Issue by RichardLuo0** [JosefNemec/PlayniteExtensions#432]
**Describe the bug**
![image](https://github.com/user-attachments/assets/9a68c0cd-a7d0-46ed-b241-b1c6aeb820ef)

**To Reproduce**
Login epic games

**Diagnostics ID**
b89d66ff-652a-48ba-8217-e00708c40ed3

**Comment by RichardLuo0** [comment]
It maybe related to proxy settings. I tried without proxy and now it works

**Comment by hasinabrar1996** [comment]
can't solve the issue.

**Comment by Mathis-Guichard** [comment]
I encountered the same issue, and it does appear to be related to a proxy, as @RichardLuo0 mentioned.

To resolve this, start by clearing your network cache. If the problem persists, try changing your IP address by restarting your router (if you have a dynamic IP). Alternatively, you can use a VPN to facilitate the login process.

It worked for me, hopefully, it'll work for you too.

**Comment by gamingexpert13** [comment]
I was having the same issue. I've had the same issue with Heroic Launcher in the past on steam deck (linux steam os) which resolved after a few hours of troubleshooting and attempting to copy the login URL it was using but modifying it so it would redirect properly, and pasting it into my browser instead of the built-in application webview. I'm not sure if any of that made a difference or if it only started working cuz it had been a few hours since it first showed up (Epic may be setting some sort of "suspicious user" flag that resets after a while, I'm not sure).

I tried opening Epic in my browser (firefox) and I was already logged in, but it did show me two new license agreement pages, so I'm not sure if those were related to the issue. I accepted then tried authenticating again in Playnite and still had the same error.

As the previous comment suggested, I tried enabling a VPN and now when authenticating epic made me solve a couple captchas and then authenticated. It's lucky that worked, because many times I've been unable to even claim free epic games in the browser if my VPN was active. It can send you through infinite captchas until you disable your VPN...

Oh, before this I did accidentally open GOG Galaxy launcher as well, so maybe Epic saw two authentication attempts from different applications and flagged my IP address as suspicious.

**Comment by CapHavito** [comment]
> **Describe the bug** ![image](https://github.com/user-attachments/assets/9a68c0cd-a7d0-46ed-b241-b1c6aeb820ef)
> 
> **To Reproduce** Login epic games
> 
> **Diagnostics ID** b89d66ff-652a-48ba-8217-e00708c40ed3

es muy fácil. Solo has de entrar en la web www.epicgames.com y al iniciar sesion te pedirá que aceptes los nuevos términos de uso. Playnite volverá a logarse de manera correcta.
