### ISSUE TITLE
PN 9.1: Amazon games update library sets newly installed games back to uninstalled

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/PlayniteExtensions#67]
**Describe the bug**
Installing a game makes playnite detect it as installed, you can play etc. Doing library update of amazon game sets the game to uninstalled again while the game is still installed. Clicking install on the game again makes playnite immediatly detect it as installed again, you can keep on repeating this 

**To Reproduce**
install new game, do library update -> game uninstalled status click install -> game immediatly installed again -> do library update -> game uninstalled again etc

**Screenshots**

https://user-images.githubusercontent.com/10714776/135670180-179023ca-9576-4dae-aef9-726f7e423ce5.mp4

**Diagnostics ID**
6f875281-2927-4ff6-860e-e7eee9ecb32a

**Comment by JosefNemec** [comment]
As far as I can tell it's an issue only with these Wallace and Gromit games. They reference them via `sku` property instead of `id`, like with all other games I tried. It basically results in the game being duplicated once you install it, you'll see it twice in your library (once with sku game id and the other with id game id).

Not sure how to handle this.

**Comment by JosefNemec** [comment]
Fixed in 2.3
