### ISSUE TITLE
Add tag to trial games

### ISSUE THREAD

**Issue by benini02** [JosefNemec/PlayniteExtensions#89]
The different demos of Origin, there are appearing as a complete game in the Playnite library.

**Comment by JosefNemec** [comment]
Can't do due to issues with Origin/EA App APIs we are using.

I spent a lot of time trying to reverse new EA App APIs but no luck making something reliable. I myself can't justify spending any more time on it since I have plenty of work to do on Playnite itself. So this is wontfix unless somebody else wants to reimplement EA library sync.
